#!/bin/sh

set -eu

printf '%s\n' \
    "BaudBound installer: downloads are paused until the first public app release." \
    "Follow development on GitHub: https://github.com/BaudBound/baudbound" >&2
exit 1
